version: 2
jobs:
  node8:
    docker:
      - image: node:8-alpine
    steps:
      - run: apk add --no-cache bash ca-certificates build-base libgit2-dev python
      - checkout
      - restore_cache:
          keys:
          - node8-{{ checksum "yarn.lock" }}
          - node8-
      - run: BUILD_ONLY=true JOBS=max yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node8-{{ checksum "yarn.lock" }}
      - run: yarn test
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
          destination: reports
  node9:
    docker:
      - image: node:9-alpine
    steps:
      - run: apk add --no-cache bash ca-certificates build-base libgit2-dev python
      - checkout
      - restore_cache:
          keys:
          - node9-{{ checksum "yarn.lock" }}
          - node9-
      - run: BUILD_ONLY=true JOBS=max yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node9-{{ checksum "yarn.lock" }}
      - run: yarn test
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
          destination: reports
workflows:
  version: 2
  build:
    jobs:
      - node8
      - node9
